import { Poppins } from "next/font/google";
import "./globals.css";
import "primeicons/primeicons.css";
import { AuthProvider } from "@/Providers/AuthProvider";
import { ThemeProvider } from "./Providers/ThemeProvider";
import "primereact/resources/themes/lara-dark-cyan/theme.css";
import { getServerSession } from "next-auth";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${poppins.className} bg-white dark:bg-[#1e0f24]`}>
        <div className="dark:bg-[#1e0f24] dark:text-white">
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              storageKey="discord"
            >
              {children}
            </ThemeProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
